# quotes.py

import random
from datetime import date

# Daily quote pool
QUOTES = [
    "Believe you can and you're halfway there.",
    "Start writing, no matter what. The water does not flow until the faucet is turned on.",
    "Every day is a fresh page.",
    "Write your heart, not your fears.",
    "You are the author of your own story.",
    "Little steps still move you forward.",
    "Today’s thoughts become tomorrow’s memories.",
    "Inhale confidence, exhale doubt.",
    "Feelings are valid — write them all down.",
    "Even blank pages have potential.",
    "Your story matters.",
    "Growth is rarely comfortable.",
    "Healing begins the moment you listen to yourself.",
    "Write through the chaos.",
    "Let the page absorb what your heart can't hold.",
    "Stillness is strength.",
    "Your words are enough.",
    "Progress, not perfection.",
    "Speak kindly to yourself.",
    "There is power in your perspective.",
    "Every moment you write, you choose yourself.",
    "This too shall pass.",
    "You’ve survived 100% of your worst days.",
    "Embrace the beauty of the unfinished.",
    "Start messy. Finish true.",
    "Honesty on paper is healing.",
    "You are allowed to feel.",
    "Words make emotions real.",
    "Journaling is self-care.",
    "The more you write, the clearer you become.",
    "Nothing is too small to document.",
    "Write like nobody will read it.",
    "Your thoughts are valid.",
    "Every page is a chance to begin again.",
    "Some days, survival is a win.",
    "You can do hard things.",
    "Let writing hold what you can’t.",
    "Your truth deserves ink.",
    "There is no wrong way to journal.",
    "It’s okay not to be okay.",
    "Trust the process.",
    "Writing heals what silence hides.",
    "Even one sentence is enough.",
    "Your emotions are messengers.",
    "Write your fears into courage.",
    "Breathe. Write. Heal.",
    "Let your mind rest on the page.",
    "Journaling is a form of meditation.",
    "You are more than your bad day.",
    "Clarity comes through writing.",
    "Write with honesty, not judgment.",
    "The page will never judge you.",
    "Today is worth recording.",
    "Writing is remembering.",
    "You can be both hurting and healing.",
    "Capture the now.",
    "Let writing reconnect you to yourself.",
    "Each word brings you closer to clarity.",
    "Some days you’ll write joy. Others, release.",
    "Release expectations — just write.",
    "Writing makes chaos manageable.",
    "You are not your thoughts — but they matter.",
    "Give your emotions a home.",
    "Every sentence is a small step toward peace.",
    "Your pen knows the way.",
    "Write your way out of confusion.",
    "In the act of writing, we reclaim ourselves.",
    "The blank page is not empty — it's possible.",
    "You don’t need the right words. Just real ones.",
    "Let writing carry what your heart can’t.",
    "Courage is choosing to feel.",
    "Your mind is worth exploring.",
    "Light lives in reflection.",
    "You are the narrator of your healing.",
    "Let your words be your mirror.",
    "Peace begins on the page.",
    "Journal like your soul depends on it.",
    "Tiny thoughts can hold big truths.",
    "Don’t edit your emotions.",
    "Sometimes writing is the only clarity.",
    "The page is your companion.",
    "Silence speaks — write what it says.",
    "Ink your growth.",
    "You’re not alone — your words are here.",
    "Let go on the page, even if you can’t in life.",
    "Document your becoming.",
    "Writing is freedom in motion.",
    "Write the things you whisper to yourself.",
    "Let your thoughts out of hiding.",
    "Write who you are — not who you think you should be.",
    "Your words are a map home.",
    "Let the pen be gentle.",
    "This moment is worthy of your attention.",
    "Pages don’t need to be pretty, just honest.",
    "There is strength in reflection.",
    "Trust your inner voice.",
    "Write as if no one is watching.",
    "Your journey is worth writing about.",
    "Emotion is energy — writing moves it.",
    "Let today’s entry be enough.",
    "Every entry is a gift to your future self.",
    "Even scribbles are sacred.",
    "Write to remember. Write to release."
]

# Return the same quote per day
def get_daily_quote():
    seed = int(date.today().strftime("%Y%m%d"))  # e.g. 20250708
    random.seed(seed)
    return random.choice(QUOTES)
